project/products/urls.py


from django.urls import path

from products.views import products, basket_add, baskets_remove
app_name = 'products'
urlpatterns = [
    path('', products, name='index'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', baskets_remove, name='baskets_remove')

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from products.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls',namespace='products')),
    path('users/', include('users.urls',namespace='users')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/users/urls.py


from django.urls import path

from users.views import login, registration, profile, logout
app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout')

]

project/products/models.py
from django.db import models
from users.models import User
# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=4, decimal_places=0)
    image = models.ImageField(upload_to='products_images')



    def __str__(self):
        return f'Мороженое:{self.name}'



class Basket(models.Model):
    user = models.ForeignKey(to=User,on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} |Мороженое: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity


project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to='user_images', null=True, blank=True)

project/users/forms.py
from django import forms

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    username = forms.CharField(widget=forms.TextInput())
    email = forms.CharField(widget=forms.EmailInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control py-4', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

project/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from products.models import Product, Basket
from users.models import User
# Create your views here.


def index(request):
    context={'title':'Lorem Ipsum',}
    return render(request,'products/index.html', context)


def products(request):
    context = {'title': 'Lorem Ipsum-товары',
               'products':Product.objects.all(),
               }
    return render(request, 'products/products.html',context)


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def baskets_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

project/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from products.models import Basket
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib.auth.decorators import login_required


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance= request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance= request.user)

    baskets = Basket.objects.filter(user=request.user)
    total_sum = 0
    total_quantity = 0
    for basket in baskets:
        total_sum = total_sum + basket.sum()
        total_quantity = total_quantity + basket.quantity

    context = {
        'title': 'Lorem Ipsum - Профиль',
        'form': form,
        'baskets': baskets,
        'total_sum': total_sum,
        'total_quantity': total_quantity,
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))




project/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Play&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    {% block css %} {%endblock%}
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <div class="container">
            <div id="clock"></div>
            <div class="nav">
                <div class="nav">
                    <span class="logo">Lorem Ipsum</span>
                    <ul class="menu">
                        <li>
                            <a href="index.html">ГЛАВНАЯ</a>
                        </li>
                        <li>
                            <a href="delivery.html">ДОСТАВКА</a>
                        </li>
                        <li>
                            <a href="{% url 'index' %}">ПРОДУКТЫ</a>
                        </li>
                        <li>
                            <a href="creators.html">СОЗДАТЕЛИ</a>
                        </li>
                    </ul>
                    <nav class=" navbar-expand-lg float-end" >
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <ul class="navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-solid fa-user"></i>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                                    </li>
                                    {% if user.is_superuser %}
                                    <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'users:logout' %}">
                                            Выйти
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            {% else %}
                            <li class="nav-item" style="text-transform: uppercase;
                            font-size: 14px;
                            letter-spacing: 0.1em;">
                                <a class="nav-link"href="{% url 'users:login' %}">Войти </a>
                            </li>
                            {%endif %}


                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
  {% block content %} {% endblock %}
    <footer>
        <div class="footer">
            <div class="footer_content">
                <div class="logo">
                    <a href="index.html"><img src="{%static 'img/ice.png' %}" alt="" ></a>
                </div>
                <div class="help">
                    <h6>Помощь</h6>
                    <a href="#">О нас</a>
                    <a href="#">Продукт</a>
                    <a href="#">Связь с нами</a>
                    <a href="#">Цена</a>

                </div>
                <div class="sub">
                    <h6>Подписки</h6>
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <a href="#"><i class="fa fa-youtube"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                </div>
                <div class="new">
                    <div class="new">
                        <h6>Подписка на новости</h6>
                        <input type="email" placeholder="Введите ваш email">
                        <button>Подписаться</button>
                </div>
            </div>
            </div>
    </footer>
     <script>
        // Функция для открытия модального окна
        function openModal() {
            document.getElementById('myModal').style.display = 'flex';
        }

        // Функция для закрытия модального окна
        function closeModal() {
            document.getElementById('myModal').style.display = 'none';
        }
    </script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

project/products/templates/products/baskets.html
{% if baskets %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                    Корзина <span class="badge badge-secondary badge-pill" style="color: black;">{{ total_quantity }}</span>
                </h4>
{% for basket in baskets %}
 <div class="card mb-3">
                    <div class="card-body" >
                        <h5 class="card-title">{{ basket.product.name }}</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item bg-light ">
                            <div class="row text-center" >
                                <div class="col-lg-4">
                                    <input name="basketID" type="number" class="form-control"
                                           value="{{ basket.quantity }}" min="0" style="border: 2px solid #000000;">
                                </div>
                                <div class="col-lg-4">{{ basket.sum }}руб.</div>
                                <div class="col-lg-4">
                                    <a href="{% url 'products:baskets_remove' basket.id %}">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
{% endfor %}

                <div class="card mb-3">
                    <div class="card-footer" style="border: 2px solid #000000;">
                        <p class="float-left">Итого</p>
                        <h4 class="float-right">{{ total_sum }} руб.</h4>
                    </div>
                </div>
                <a class="btn btn-success btn-danger float-right" href="#" >
                    Оформить заказ
                </a>
{% else %}
<h4 class="mt-3 mb-3 text-center">
                    Корзина пуста
                </h4>
{% endif %}

project/products/templates/products/index.html
{% extends  'products/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{%static 'css/products.css' %}">
{% endblock %}


{% block content %}
    <section>
        <div class="row">
            <img src="{%static 'img/123.png' %}" alt="img123">
            <div class="why">
                <h3>Почему мы?</h3>
                <h1>Мы делаем это вкусно!</h1>
                <p>Вкусно, дешево, а главное большой выбор. Мороженое Lorem ipsum вы заслуживаете того, чтобы съесть сегодня сладкое</p>
                <button><img class="small-ice" img src="{%static 'img/ice1.png' %}" alt="ice1">60+</button>
                <button><img class="small-ice" img src="{%static 'img/ice2.png' %}" alt="ice1">120+</button>
                <button><img class="small-ice" img src="{%static 'img/ice3.png' %}" alt="ice1">180+</button>
                <div> <button onclick="openModal()">Купить</button></div>

            </div>
        </div>
    </section>



    <div id="myModal" class="modal">
        <span class="close-btn" onclick="closeModal()">&times;</span>
        <div class="containers">
                <div class="tovar">
                    <div class="product">
                        <p><img src="{%static 'img/moroz1.png' %}" alt=""></p>
                        <p> Ванильный рожок</p>

                  </div>
                </div>
                <div class="tovar">
                    <div class="product">
                        <p><img src="{%static 'img/moroz2.png' %}" alt=""></p>
                        <p>Рожок с шоколадом</p>

                  </div>
                </div>
                <div class="tovar">
                   <div class="product">
                    <p><img src="{%static 'img/moroz3.png' %}" alt=""></p>
                    <p>Фисташковый рожок</p>
                  </div>

                </div>

        </div>
            <a href="{% url 'products:index' %}">Подробнее</a>
    </div>
{% endblock%}

project/products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{%static 'css/tovar.css' %}">
{% endblock %}


{%block content%}
   <div class="tovars">
    <div class="containers">
        {% for product in products %}
         <div class="tovar">
            <div class="product">
                <p><img src="{{ product.image.url }}" alt=""></p>
                <p>{{ product.name }}</p>
                <p class="product-price">{{ product.price }}р</p>
                 <div class="card-footer text-start">
                    <a class="btn btn-outline-success " href="{% url 'products:basket_add' product.id %}">В корзину</a>
                </div>
          </div>
        </div>
        {% endfor %}

</div>
        </div>
   </div>
{% endblock %}

project/users/templates/users/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>

<body>
    {% block content %} {% endblock %}
</body>

</html>

project/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
   <div class="col-lg-5">
       {% if messages or form.non_field_errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert"
             style="margin-top: 50px;">
            {%  if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            {% else %}
                {{ form.non_field_errors }}
            {% endif %}
        </div>
       {% endif %}

    <div class="container">
        <h2>Авторизация</h2>
        <form id="registrationForm" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}

            <label for="{{ form.username.id_for_label }}">Имя пользователя:</label>
           {{ form.username }}

            <label for="{{ form.password.id_for_label }}">Пароль:</label>
            {{ form.password }}

            <input class="btn btn-primary" type="submit" value="Вход" >
            <button type="button" class="cancel" onclick="window.location.href='{% url 'index' %}'">Отмена</button>
        <p>Нужен аккаунт? <a href="{% url 'users:registration' %}">Регистрация</a></p>
        </form>
<!--        <script>-->
<!--            document.getElementById('registrationForm').addEventListener('submit', function (event) {-->
<!--                window.location.href = "{% url 'index' %}";-->
<!--                event.preventDefault();-->
<!--            });-->
<!--        </script>-->
    </div>
{% endblock %}

project/users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content%}
    <div class="container" style="height: 1000px;">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-sm-start">
                    <img width="200" height="200"
                         src="{% if user.image %} {{ users.image.url }} {% else %} {% static 'img/profile.png' %}{% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row " style="display: inline">
                        <div class="col-lg-6" >
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                               {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                               {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                           {{ form.username }}
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-dark btn-block" type="submit" value="Сохранить" >
                        </div>
                    </div>
                    </div>
                    </form>
            </div>
            <div class="col-lg-5">
                {% include 'products/baskets.html' %}
            </div>
        </div>
    </div>
{% endblock %}

project/users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
<div class="row justify-content-center">
        <div class="col-lg-7">
            {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{form.errors }}

            </div>
            {% endif %}

    <div class="container">
        <h2>Регистрация</h2>
        <form id="registrationForm" action="{% url 'users:registration' %}" method="post">
            {% csrf_token %}
            <label for="{{ form.first_name.id_for_label }}">Имя:</label>
           {{ form.first_name }}
            <label for="{{ form.last_name.id_for_label }}">Фамилия:</label>
           {{ form.last_name }}
            <label for="{{ form.username.id_for_label }}">Имя пользователя:</label>
            {{ form.username }}

            <label for="{{ form.email.id_for_label }}">Электронная почта:</label>
            {{ form.email }}

            <label for="{{ form.password1.id_for_label }}">Пароль:</label>
            {{ form.password1 }}
            <label for="{{ form.password2.id_for_label }}">Повторите пароль:</label>
           {{ form.password2 }}

            <input class="btn btn-primary" type="submit" value="Зарегистрироваться" >
            <button type="button" class="cancel" onclick="window.location.href='{% url 'index' %}'">Отмена</button>
        </form>
        <p>Уже есть аккаунт? <a href="{% url 'users:login' %}">Войти</a></p>
<!--        <script>-->
<!--            document.getElementById('registrationForm').addEventListener('submit', function (event) {-->
<!--                window.location.href = "{% url 'index' %}";-->
<!--                event.preventDefault();-->
<!--            });-->
<!--        </script>-->
    </div>
{% endblock %}